sudo: required
language: go
services:
  - docker

go:
  - 1.x

install:
  - mkdir -p $GOPATH/bin
  - go get -u github.com/go-playground/overalls
  - go get -u github.com/Masterminds/glide
  - go get -u github.com/jteeuwen/go-bindata/go-bindata
  - make deps
  - make build-assets

script:
- make test
