sudo: required
language: go
services:
  - docker

go:
  - 1.x

before_install:
  - docker-compose -f ./docker-compose.yml up -d

install:
  - mkdir -p $GOPATH/bin
  - go get github.com/go-playground/overalls
  - make deps

script:
- make test
