#%RAML 1.0
title: News Today
version: v1
documentation:
  - title: Introduction
    content: |
      This is the READ API documentation for the News-Today API Service.
mediaType: application/json
baseUri: https://kornienko.site:8090/{version}/
